travis:
  secure:
    BINSTAR_TOKEN: uAEC+rlfN8IyLvGVOkt8OI//kjJs/7g5ta+hB+UOaheFsJrLS3DZlWcmHwg+4KC/E34/9i2BokoljoprWoXZ02Q9EQjGdAMFCkvbg+rdoYvRXuEFtBbYvPVjncfkk4tybbwleFnEbrP4gORVeuRixKuhW7QbnamBsZyggbbCDbB6Rcq0kx5nf+k6u/3/CzGQUQ66Q6f8GXZRsJhisHfP2ak8B3Z6KNl0LULmImTmg1hgMJsbp8cORlXgjp58ujvKBCPk5u145nPZuqiSe4olssA9XXPk+28nSIXv5M537sIJzNSEiqPhjGrjLpNxy8hQKAwUDaIzD2zgks+WCi98MB8FONntqlTIfg5E4SA1psJAwxJZiBX1e3eCT6aSNRrk9Ae+DAizAPWcfnxvWfLye1Fuwjwn1VABsErmldnGGb9OfOWw/cYt+K5+fkkRArK7CkC9gRYflw1zYDB9EvCR4FSMAhLeVwrVuzd8/PadlevD3n1NQilbBeSo6HRIPfXiGerNCuDmiy0x2JjHqRG3FhPODAUxdBc+JFRf7NVU1bLr4LpQ5WcsDFRaFgeWZOUOV/yJPdFk6YtrKtDFCb18OD/lYmWBcJTKUeH3/qz2OfCJ2eKFc/4PR5031hcX3b+ypE57vMETdBvYTS2i8hYUtKDBkXt/A9FOGxhkh69DB30=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
